version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: english_learning_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: english_learning_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: english_learning_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/english_learning_app?schema=public
    depends_on:
      - postgres

volumes:
  postgres_data: